# Changes here will be overwritten by Copier
_commit: 5307c9e
_src_path: https://github.com/oarepo/nrp-app-copier
languages: ''
repository_description: Physica.science is an open repository of physics data spanning
    all scales, from particle physics to crystallography. It provides structured,
    reusable datasets to support reproducible and cross-disciplinary research.
repository_human_name: Physica.science
