[project]
name = "physica"
version = "1.0.0"
description = "Physics Repository is an open repository of physics data spanning all scales, from particle physics to crystallography. It provides structured, reusable datasets to support reproducible and cross-disciplinary research."
packages = []
authors = []
dependencies = [
    "oarepo[s3,rdm]>=14.2.1b10.dev6,<15.0.0",
    "oarepo-app[production,ccmm]==4.0.0",
]
requires-python = ">=3.14,<3.15"

[project.entry-points."invenio_assets.webpack"]
i18n = "i18n.webpack:theme"
components = "ui.components.webpack:theme"
ui_particles = "ui.particles.webpack:theme"
ui_detectors = "ui.detectors.webpack:theme"
ui_fram = "ui.fram.webpack:theme"
ui_atlas_itk = "ui.atlas_itk.webpack:theme"

[project.entry-points."invenio_i18n.translations"]
translations = "i18n"

[project.entry-points."invenio_db.alembic"]
repository = "common:alembic"

[project.entry-points."invenio_base.blueprints"]
ui_particles = "ui.particles:create_blueprint"
ui_detectors = "ui.detectors:create_blueprint"
ui_fram = "ui.fram:create_blueprint"
ui_atlas_itk = "ui.atlas_itk:create_blueprint"

[project.entry-points."invenio_base.finalize_app"]
ui_particles = "ui.particles:finalize_app"
ui_detectors = "ui.detectors:finalize_app"
ui_fram = "ui.fram:finalize_app"
ui_atlas_itk = "ui.atlas_itk:finalize_app"

[tool.uv.build-backend]
module-root = ""
module-name = [
    "common",
    "i18n",
    "ui",
    "models"
]

[build-system]
requires = [
    "uv_build>=0.8.7,<0.9.0",
]
build-backend = "uv_build"
