# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-License-Identifier: MIT

"""Create physica tables."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
import invenio_db

# revision identifiers, used by Alembic.
revision = '1789039346'
down_revision = '1789039339'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_itk_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_atlas_itk_metadata_version')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_atlas_itk_metadata_version_end_transaction_id'), 'atlas_itk_metadata_version', ['end_transaction_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_metadata_version_operation_type'), 'atlas_itk_metadata_version', ['operation_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_metadata_version_transaction_id'), 'atlas_itk_metadata_version', ['transaction_id'], unique=False, if_not_exists=True)
    op.create_table('atlas_itk_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_parent_metadata')),
    if_not_exists=True
    )
    op.create_table('fram_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_fram_metadata_version')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_fram_metadata_version_end_transaction_id'), 'fram_metadata_version', ['end_transaction_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_metadata_version_operation_type'), 'fram_metadata_version', ['operation_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_metadata_version_transaction_id'), 'fram_metadata_version', ['transaction_id'], unique=False, if_not_exists=True)
    op.create_table('fram_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_parent_metadata')),
    if_not_exists=True
    )
    op.create_table('particles_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_particles_metadata_version')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_particles_metadata_version_end_transaction_id'), 'particles_metadata_version', ['end_transaction_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_metadata_version_operation_type'), 'particles_metadata_version', ['operation_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_metadata_version_transaction_id'), 'particles_metadata_version', ['transaction_id'], unique=False, if_not_exists=True)
    op.create_table('particles_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_parent_metadata')),
    if_not_exists=True
    )
    op.create_table('sipm_metadata_version',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('deletion_status', sa.String(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), autoincrement=False, nullable=True),
    sa.Column('version_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('index', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name=op.f('pk_sipm_metadata_version')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_sipm_metadata_version_end_transaction_id'), 'sipm_metadata_version', ['end_transaction_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_metadata_version_operation_type'), 'sipm_metadata_version', ['operation_type'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_metadata_version_transaction_id'), 'sipm_metadata_version', ['transaction_id'], unique=False, if_not_exists=True)
    op.create_table('sipm_parent_metadata',
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('workflow', sa.String(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_parent_metadata')),
    if_not_exists=True
    )
    op.create_table('atlas_itk_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_atlas_itk_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_atlas_itk_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['atlas_itk_parent_metadata.id'], name=op.f('fk_atlas_itk_draft_metadata_parent_id_atlas_itk_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_draft_metadata')),
    if_not_exists=True
    )
    op.create_table('atlas_itk_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_atlas_itk_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_atlas_itk_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['atlas_itk_parent_metadata.id'], name=op.f('fk_atlas_itk_metadata_parent_id_atlas_itk_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_metadata')),
    if_not_exists=True
    )
    op.create_table('fram_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_fram_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_fram_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['fram_parent_metadata.id'], name=op.f('fk_fram_draft_metadata_parent_id_fram_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_draft_metadata')),
    if_not_exists=True
    )
    op.create_table('fram_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_fram_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_fram_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['fram_parent_metadata.id'], name=op.f('fk_fram_metadata_parent_id_fram_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_metadata')),
    if_not_exists=True
    )
    op.create_table('particles_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_particles_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_particles_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['particles_parent_metadata.id'], name=op.f('fk_particles_draft_metadata_parent_id_particles_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_draft_metadata')),
    if_not_exists=True
    )
    op.create_table('particles_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_particles_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_particles_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['particles_parent_metadata.id'], name=op.f('fk_particles_metadata_parent_id_particles_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_metadata')),
    if_not_exists=True
    )
    op.create_table('sipm_draft_metadata',
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('fork_version_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', invenio_db.shared.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_sipm_draft_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_sipm_draft_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['sipm_parent_metadata.id'], name=op.f('fk_sipm_draft_metadata_parent_id_sipm_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_draft_metadata')),
    if_not_exists=True
    )
    op.create_table('sipm_metadata',
    sa.Column('bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('media_bucket_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('deletion_status', sa.String(length=1), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['bucket_id'], ['files_bucket.id'], name=op.f('fk_sipm_metadata_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['media_bucket_id'], ['files_bucket.id'], name=op.f('fk_sipm_metadata_media_bucket_id_files_bucket')),
    sa.ForeignKeyConstraint(['parent_id'], ['sipm_parent_metadata.id'], name=op.f('fk_sipm_metadata_parent_id_sipm_parent_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_metadata')),
    if_not_exists=True
    )
    op.create_table('atlas_itk_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_atlas_itk_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['atlas_itk_draft_metadata.id'], name=op.f('fk_atlas_itk_draft_files_record_id_atlas_itk_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_draft_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_atlas_itk_draft_files_object_version_id'), 'atlas_itk_draft_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_draft_files_record_id'), 'atlas_itk_draft_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_atlas_itk_draft_files_record_id_key', 'atlas_itk_draft_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('atlas_itk_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_atlas_itk_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['atlas_itk_draft_metadata.id'], name=op.f('fk_atlas_itk_draft_media_files_record_id_atlas_itk_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_draft_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_atlas_itk_draft_media_files_object_version_id'), 'atlas_itk_draft_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_draft_media_files_record_id'), 'atlas_itk_draft_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_atlas_itk_draft_media_files_record_id_key', 'atlas_itk_draft_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('atlas_itk_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_atlas_itk_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['atlas_itk_metadata.id'], name=op.f('fk_atlas_itk_files_record_id_atlas_itk_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_atlas_itk_files_object_version_id'), 'atlas_itk_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_files_record_id'), 'atlas_itk_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_atlas_itk_files_record_id_key', 'atlas_itk_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('atlas_itk_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_atlas_itk_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['atlas_itk_metadata.id'], name=op.f('fk_atlas_itk_media_files_record_id_atlas_itk_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_itk_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_atlas_itk_media_files_object_version_id'), 'atlas_itk_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_atlas_itk_media_files_record_id'), 'atlas_itk_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_atlas_itk_media_files_record_id_key', 'atlas_itk_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('atlas_itk_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['atlas_itk_metadata.id'], name=op.f('fk_atlas_itk_parent_record_state_latest_id_atlas_itk_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['atlas_itk_draft_metadata.id'], name=op.f('fk_atlas_itk_parent_record_state_next_draft_id_atlas_itk_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['atlas_itk_parent_metadata.id'], name=op.f('fk_atlas_itk_parent_record_state_parent_id_atlas_itk_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_atlas_itk_parent_record_state')),
    if_not_exists=True
    )
    op.create_table('atlas_itk_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_atlas_itk_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['atlas_itk_parent_metadata.id'], name=op.f('fk_atlas_itk_parents_community_record_id_atlas_itk_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_atlas_itk_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_atlas_itk_parents_community')),
    if_not_exists=True
    )
    op.create_table('fram_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_fram_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['fram_draft_metadata.id'], name=op.f('fk_fram_draft_files_record_id_fram_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_draft_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_fram_draft_files_object_version_id'), 'fram_draft_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_draft_files_record_id'), 'fram_draft_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_fram_draft_files_record_id_key', 'fram_draft_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('fram_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_fram_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['fram_draft_metadata.id'], name=op.f('fk_fram_draft_media_files_record_id_fram_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_draft_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_fram_draft_media_files_object_version_id'), 'fram_draft_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_draft_media_files_record_id'), 'fram_draft_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_fram_draft_media_files_record_id_key', 'fram_draft_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('fram_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_fram_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['fram_metadata.id'], name=op.f('fk_fram_files_record_id_fram_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_fram_files_object_version_id'), 'fram_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_files_record_id'), 'fram_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_fram_files_record_id_key', 'fram_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('fram_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_fram_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['fram_metadata.id'], name=op.f('fk_fram_media_files_record_id_fram_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fram_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_fram_media_files_object_version_id'), 'fram_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_fram_media_files_record_id'), 'fram_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_fram_media_files_record_id_key', 'fram_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('fram_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['fram_metadata.id'], name=op.f('fk_fram_parent_record_state_latest_id_fram_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['fram_draft_metadata.id'], name=op.f('fk_fram_parent_record_state_next_draft_id_fram_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['fram_parent_metadata.id'], name=op.f('fk_fram_parent_record_state_parent_id_fram_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_fram_parent_record_state')),
    if_not_exists=True
    )
    op.create_table('fram_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_fram_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['fram_parent_metadata.id'], name=op.f('fk_fram_parents_community_record_id_fram_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_fram_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_fram_parents_community')),
    if_not_exists=True
    )
    op.create_table('particles_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_particles_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['particles_draft_metadata.id'], name=op.f('fk_particles_draft_files_record_id_particles_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_draft_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_particles_draft_files_object_version_id'), 'particles_draft_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_draft_files_record_id'), 'particles_draft_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_particles_draft_files_record_id_key', 'particles_draft_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('particles_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_particles_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['particles_draft_metadata.id'], name=op.f('fk_particles_draft_media_files_record_id_particles_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_draft_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_particles_draft_media_files_object_version_id'), 'particles_draft_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_draft_media_files_record_id'), 'particles_draft_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_particles_draft_media_files_record_id_key', 'particles_draft_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('particles_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_particles_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['particles_metadata.id'], name=op.f('fk_particles_files_record_id_particles_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_particles_files_object_version_id'), 'particles_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_files_record_id'), 'particles_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_particles_files_record_id_key', 'particles_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('particles_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_particles_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['particles_metadata.id'], name=op.f('fk_particles_media_files_record_id_particles_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_particles_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_particles_media_files_object_version_id'), 'particles_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_particles_media_files_record_id'), 'particles_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_particles_media_files_record_id_key', 'particles_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('particles_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['particles_metadata.id'], name=op.f('fk_particles_parent_record_state_latest_id_particles_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['particles_draft_metadata.id'], name=op.f('fk_particles_parent_record_state_next_draft_id_particles_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['particles_parent_metadata.id'], name=op.f('fk_particles_parent_record_state_parent_id_particles_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_particles_parent_record_state')),
    if_not_exists=True
    )
    op.create_table('particles_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_particles_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['particles_parent_metadata.id'], name=op.f('fk_particles_parents_community_record_id_particles_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_particles_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_particles_parents_community')),
    if_not_exists=True
    )
    op.create_table('sipm_draft_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_sipm_draft_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['sipm_draft_metadata.id'], name=op.f('fk_sipm_draft_files_record_id_sipm_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_draft_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_sipm_draft_files_object_version_id'), 'sipm_draft_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_draft_files_record_id'), 'sipm_draft_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_sipm_draft_files_record_id_key', 'sipm_draft_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('sipm_draft_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_sipm_draft_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['sipm_draft_metadata.id'], name=op.f('fk_sipm_draft_media_files_record_id_sipm_draft_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_draft_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_sipm_draft_media_files_object_version_id'), 'sipm_draft_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_draft_media_files_record_id'), 'sipm_draft_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_sipm_draft_media_files_record_id_key', 'sipm_draft_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('sipm_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_sipm_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['sipm_metadata.id'], name=op.f('fk_sipm_files_record_id_sipm_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_sipm_files_object_version_id'), 'sipm_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_files_record_id'), 'sipm_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_sipm_files_record_id_key', 'sipm_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('sipm_media_files',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('json', sa.JSON().with_variant(sqlalchemy_utils.types.json.JSONType(), 'mysql').with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql').with_variant(sqlalchemy_utils.types.json.JSONType(), 'sqlite'), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated', invenio_db.shared.UTCDateTime(timezone=True), nullable=False),
    sa.Column('key', sa.Text().with_variant(mysql.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('object_version_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['object_version_id'], ['files_object.version_id'], name=op.f('fk_sipm_media_files_object_version_id_files_object'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['sipm_metadata.id'], name=op.f('fk_sipm_media_files_record_id_sipm_metadata'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sipm_media_files')),
    if_not_exists=True
    )
    op.create_index(op.f('ix_sipm_media_files_object_version_id'), 'sipm_media_files', ['object_version_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_sipm_media_files_record_id'), 'sipm_media_files', ['record_id'], unique=False, if_not_exists=True)
    op.create_index('uidx_sipm_media_files_record_id_key', 'sipm_media_files', ['record_id', 'key'], unique=True, if_not_exists=True)
    op.create_table('sipm_parent_record_state',
    sa.Column('latest_index', sa.Integer(), nullable=True),
    sa.Column('parent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('latest_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('next_draft_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['latest_id'], ['sipm_metadata.id'], name=op.f('fk_sipm_parent_record_state_latest_id_sipm_metadata')),
    sa.ForeignKeyConstraint(['next_draft_id'], ['sipm_draft_metadata.id'], name=op.f('fk_sipm_parent_record_state_next_draft_id_sipm_draft_metadata')),
    sa.ForeignKeyConstraint(['parent_id'], ['sipm_parent_metadata.id'], name=op.f('fk_sipm_parent_record_state_parent_id_sipm_parent_metadata'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_sipm_parent_record_state')),
    if_not_exists=True
    )
    op.create_table('sipm_parents_community',
    sa.Column('community_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('record_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('request_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities_metadata.id'], name=op.f('fk_sipm_parents_community_community_id_communities_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['sipm_parent_metadata.id'], name=op.f('fk_sipm_parents_community_record_id_sipm_parent_metadata'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request_metadata.id'], name=op.f('fk_sipm_parents_community_request_id_request_metadata'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('community_id', 'record_id', name=op.f('pk_sipm_parents_community')),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sipm_parents_community')
    op.drop_table('sipm_parent_record_state')
    op.drop_index('uidx_sipm_media_files_record_id_key', table_name='sipm_media_files')
    op.drop_index(op.f('ix_sipm_media_files_record_id'), table_name='sipm_media_files')
    op.drop_index(op.f('ix_sipm_media_files_object_version_id'), table_name='sipm_media_files')
    op.drop_table('sipm_media_files')
    op.drop_index('uidx_sipm_files_record_id_key', table_name='sipm_files')
    op.drop_index(op.f('ix_sipm_files_record_id'), table_name='sipm_files')
    op.drop_index(op.f('ix_sipm_files_object_version_id'), table_name='sipm_files')
    op.drop_table('sipm_files')
    op.drop_index('uidx_sipm_draft_media_files_record_id_key', table_name='sipm_draft_media_files')
    op.drop_index(op.f('ix_sipm_draft_media_files_record_id'), table_name='sipm_draft_media_files')
    op.drop_index(op.f('ix_sipm_draft_media_files_object_version_id'), table_name='sipm_draft_media_files')
    op.drop_table('sipm_draft_media_files')
    op.drop_index('uidx_sipm_draft_files_record_id_key', table_name='sipm_draft_files')
    op.drop_index(op.f('ix_sipm_draft_files_record_id'), table_name='sipm_draft_files')
    op.drop_index(op.f('ix_sipm_draft_files_object_version_id'), table_name='sipm_draft_files')
    op.drop_table('sipm_draft_files')
    op.drop_table('particles_parents_community')
    op.drop_table('particles_parent_record_state')
    op.drop_index('uidx_particles_media_files_record_id_key', table_name='particles_media_files')
    op.drop_index(op.f('ix_particles_media_files_record_id'), table_name='particles_media_files')
    op.drop_index(op.f('ix_particles_media_files_object_version_id'), table_name='particles_media_files')
    op.drop_table('particles_media_files')
    op.drop_index('uidx_particles_files_record_id_key', table_name='particles_files')
    op.drop_index(op.f('ix_particles_files_record_id'), table_name='particles_files')
    op.drop_index(op.f('ix_particles_files_object_version_id'), table_name='particles_files')
    op.drop_table('particles_files')
    op.drop_index('uidx_particles_draft_media_files_record_id_key', table_name='particles_draft_media_files')
    op.drop_index(op.f('ix_particles_draft_media_files_record_id'), table_name='particles_draft_media_files')
    op.drop_index(op.f('ix_particles_draft_media_files_object_version_id'), table_name='particles_draft_media_files')
    op.drop_table('particles_draft_media_files')
    op.drop_index('uidx_particles_draft_files_record_id_key', table_name='particles_draft_files')
    op.drop_index(op.f('ix_particles_draft_files_record_id'), table_name='particles_draft_files')
    op.drop_index(op.f('ix_particles_draft_files_object_version_id'), table_name='particles_draft_files')
    op.drop_table('particles_draft_files')
    op.drop_table('fram_parents_community')
    op.drop_table('fram_parent_record_state')
    op.drop_index('uidx_fram_media_files_record_id_key', table_name='fram_media_files')
    op.drop_index(op.f('ix_fram_media_files_record_id'), table_name='fram_media_files')
    op.drop_index(op.f('ix_fram_media_files_object_version_id'), table_name='fram_media_files')
    op.drop_table('fram_media_files')
    op.drop_index('uidx_fram_files_record_id_key', table_name='fram_files')
    op.drop_index(op.f('ix_fram_files_record_id'), table_name='fram_files')
    op.drop_index(op.f('ix_fram_files_object_version_id'), table_name='fram_files')
    op.drop_table('fram_files')
    op.drop_index('uidx_fram_draft_media_files_record_id_key', table_name='fram_draft_media_files')
    op.drop_index(op.f('ix_fram_draft_media_files_record_id'), table_name='fram_draft_media_files')
    op.drop_index(op.f('ix_fram_draft_media_files_object_version_id'), table_name='fram_draft_media_files')
    op.drop_table('fram_draft_media_files')
    op.drop_index('uidx_fram_draft_files_record_id_key', table_name='fram_draft_files')
    op.drop_index(op.f('ix_fram_draft_files_record_id'), table_name='fram_draft_files')
    op.drop_index(op.f('ix_fram_draft_files_object_version_id'), table_name='fram_draft_files')
    op.drop_table('fram_draft_files')
    op.drop_table('atlas_itk_parents_community')
    op.drop_table('atlas_itk_parent_record_state')
    op.drop_index('uidx_atlas_itk_media_files_record_id_key', table_name='atlas_itk_media_files')
    op.drop_index(op.f('ix_atlas_itk_media_files_record_id'), table_name='atlas_itk_media_files')
    op.drop_index(op.f('ix_atlas_itk_media_files_object_version_id'), table_name='atlas_itk_media_files')
    op.drop_table('atlas_itk_media_files')
    op.drop_index('uidx_atlas_itk_files_record_id_key', table_name='atlas_itk_files')
    op.drop_index(op.f('ix_atlas_itk_files_record_id'), table_name='atlas_itk_files')
    op.drop_index(op.f('ix_atlas_itk_files_object_version_id'), table_name='atlas_itk_files')
    op.drop_table('atlas_itk_files')
    op.drop_index('uidx_atlas_itk_draft_media_files_record_id_key', table_name='atlas_itk_draft_media_files')
    op.drop_index(op.f('ix_atlas_itk_draft_media_files_record_id'), table_name='atlas_itk_draft_media_files')
    op.drop_index(op.f('ix_atlas_itk_draft_media_files_object_version_id'), table_name='atlas_itk_draft_media_files')
    op.drop_table('atlas_itk_draft_media_files')
    op.drop_index('uidx_atlas_itk_draft_files_record_id_key', table_name='atlas_itk_draft_files')
    op.drop_index(op.f('ix_atlas_itk_draft_files_record_id'), table_name='atlas_itk_draft_files')
    op.drop_index(op.f('ix_atlas_itk_draft_files_object_version_id'), table_name='atlas_itk_draft_files')
    op.drop_table('atlas_itk_draft_files')
    op.drop_table('sipm_metadata')
    op.drop_table('sipm_draft_metadata')
    op.drop_table('particles_metadata')
    op.drop_table('particles_draft_metadata')
    op.drop_table('fram_metadata')
    op.drop_table('fram_draft_metadata')
    op.drop_table('atlas_itk_metadata')
    op.drop_table('atlas_itk_draft_metadata')
    op.drop_table('sipm_parent_metadata')
    op.drop_index(op.f('ix_sipm_metadata_version_transaction_id'), table_name='sipm_metadata_version')
    op.drop_index(op.f('ix_sipm_metadata_version_operation_type'), table_name='sipm_metadata_version')
    op.drop_index(op.f('ix_sipm_metadata_version_end_transaction_id'), table_name='sipm_metadata_version')
    op.drop_table('sipm_metadata_version')
    op.drop_table('particles_parent_metadata')
    op.drop_index(op.f('ix_particles_metadata_version_transaction_id'), table_name='particles_metadata_version')
    op.drop_index(op.f('ix_particles_metadata_version_operation_type'), table_name='particles_metadata_version')
    op.drop_index(op.f('ix_particles_metadata_version_end_transaction_id'), table_name='particles_metadata_version')
    op.drop_table('particles_metadata_version')
    op.drop_table('fram_parent_metadata')
    op.drop_index(op.f('ix_fram_metadata_version_transaction_id'), table_name='fram_metadata_version')
    op.drop_index(op.f('ix_fram_metadata_version_operation_type'), table_name='fram_metadata_version')
    op.drop_index(op.f('ix_fram_metadata_version_end_transaction_id'), table_name='fram_metadata_version')
    op.drop_table('fram_metadata_version')
    op.drop_table('atlas_itk_parent_metadata')
    op.drop_index(op.f('ix_atlas_itk_metadata_version_transaction_id'), table_name='atlas_itk_metadata_version')
    op.drop_index(op.f('ix_atlas_itk_metadata_version_operation_type'), table_name='atlas_itk_metadata_version')
    op.drop_index(op.f('ix_atlas_itk_metadata_version_end_transaction_id'), table_name='atlas_itk_metadata_version')
    op.drop_table('atlas_itk_metadata_version')
    # ### end Alembic commands ###
