# Changes here will be overwritten by Copier
_commit: 47fe7e1
_src_path: https://github.com/oarepo/nrp-model-copier
base_model: rdm_complete
model_description: 'Fermilab silicon photomultiplier datasets

    '
model_human_name: Detectors
